{{- if and (.Values.configFileYaml) (ne .Values.configFileYaml "") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "webdav.fullname" . }}-config
  namespace: default
  labels:
    app: {{ template "webdav.name" . }}
    chart: {{ template "webdav.chart" . }}
    release: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
    heritage: {{ .Release.Service }}
data:
  config.yaml: {{- toYaml .Values.configFileYaml | nindent 4 -}}
{{- end }}