apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "webdav.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "webdav.name" . }}
    chart: {{ template "webdav.chart" . }}
    release: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/app-root: /webdav
    nginx.ingress.kubernetes.io/auth-keepalive-timeout: "3600"
    nginx.ingress.kubernetes.io/client-body-buffer-size: 512M
    nginx.ingress.kubernetes.io/proxy-buffer-size: 512M
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "360"
    nginx.ingress.kubernetes.io/proxy-next-upstream-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "360"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "on"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "360"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: {{ template "webdav.fullname" . }}
                port:
                  number: {{ .Values.service.httpPort }}
            path: /webdav(/|$)(.*)
            pathType: ImplementationSpecific