{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) ( .Values.persistence.pv.enabled) -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-{{ template "webdav.fullname" . }}
  labels:
    app: {{ template "webdav.name" . }}
    chart: {{ template "webdav.chart" . }}
    release: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - {{ .Values.persistence.accessModes | quote }}
  capacity:
  {{- if not .Values.persistence.size }}
    storage: 100Mi
  {{- else }}
    storage: {{ .Values.persistence.size | quote }}
  {{- end }}
  claimRef:
    name: {{ template "webdav.fullname" . }}
    namespace: {{ .Release.Namespace }}
  {{- if .Values.persistence.pv.hostPath.path }}
  {{- if (eq "-" .Values.persistence.pv.hostPath.path) }}
  hostPath:
    path: /tmp/{{ .Release.Namespace }}/{{ .Release.Name }}/{{ template "webdav.name" . }}
  {{- else }}
  hostPath:
    path: {{ .Values.persistence.pv.hostPath.path | quote }}
  {{- end }}
  {{- end }}
  persistentVolumeReclaimPolicy: Retain
  {{- if .Values.persistence.pv.storageClass }}
  {{- if (eq "-" .Values.persistence.pv.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.persistence.pv.storageClass | quote }}
  {{- end }}
  {{- end }}
{{- end }}

