apiVersion: v1
kind: Service
metadata:
  name: {{ template "webdav.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "webdav.name" . }}
    chart: {{ template "webdav.chart" . }}
    release: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.serviceType }}
  ports:
    - name: http-port
      protocol: TCP
      port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.service.httpPort }}
      {{- if (and (eq .Values.service.serviceType "NodePort") (not (empty .Values.service.httpNodePort))) }}
      nodePort: {{.Values.service.httpNodePort}}
      {{- end }}
  selector:
    app: {{ template "webdav.name" . }}
    release: {{ .Release.Name }}