persistence:
  enabled: true
  existingClaim: selenium-node
  size: 15Gi
  accessModes: ReadWriteMany
  pv:
    enabled: true
    hostPath:
      path: /testops/local/selenium

image:
  registry: ${wsgidav.image.registry}
  name: ${wsgidav.image.name}
  tag: ${wsgidav.image.tag}
  pullPolicy: IfNotPresent

service:
  serviceType: ClusterIP
  httpPort: 8080
  #httpNodePort: 30080

extraEnvironmentVariables:
  - name: CONFIG_FILE
    value: /opt/bin/config.yaml
  - name: ROOT_PATH
    value: /share
  - name: SERVER
    value: cheroot
extraEnvFrom:
  - configMapRef:
      name: '{{ template "webdav.fullname" . }}-config'

configs: |-
  simple_dc:
    user_mapping:
      '*':  true
  
  provider_mapping: {}
  
  dir_browser:
    enable: true
    ignore:
      - '.DS_Store'
      - 'Thumbs.db'
      - '._*'
    directory_slash: false
    icon: false
    response_trailer: false
    show_user: false
    show_logout: true
    davmount: false
    davmount_links: false
    ms_sharepoint_support: true
    libre_office_support: true
    htdocs_path: null